
---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

```

Column {data-width=650}
-----------------------------------------------------------------------


```{r}
set.seed(1) ##end up with the same random sample
data(instacart) 
data_instacart = janitor::clean_names(instacart) %>% 
group_by(aisle_id) %>%
summarize(n = n()) 
```

###plotly scatterplotd
```{r}
data_instacart %>%
  plot_ly(x = ~aisle_id, y = ~n, type = "scatter") %>% 
          layout(
            title = "Orders of each aisle_id ",
              xaxis = list(title = "Aisle_id"),
              yaxis = list(title = "Orders of each aisle_id")
          )
```
Column {data-width=350}
-----------------------------------------------------------------------

### plotly boxplot
```{r}
janitor::clean_names(instacart) %>%
filter(order_number>40) %>% 
group_by(department) %>%
plot_ly(x = ~department, y = ~order_number, color = ~department, type = "box", colors = "Set2") %>%
layout( title = "Order_number vs Department"
        )
```

### bar charts
```{r}
janitor::clean_names(instacart) %>%
  count(department) %>% 
  top_n(8) %>% 
  mutate(department = fct_reorder(department, n)) %>% 
   plot_ly(x = ~department, y = ~n, color = ~department, type = "bar") %>%
layout( title = "Number of orders in each department",
         xaxis = list(title = "Department"),
              yaxis = list(title = "Orders in each Department"))
```

