---
title: "Resume"
---

915 West End Avenue, New York, New York 10025 | (781)530-8509 | jw3726@columbia.edu

**EDUCATION**

Columbia University, Mailman School Of Public Health           New York, NY

*Master of Science in Biostatistics*                      Expected May 2020

Relevant Courses: Probability, Data Science, Biostatistical Methods, Epidemiology 

Brandeis University                                             Waltham, MA

*Bachelor of Arts in Chemistry and Economics*                     May 2018                  
Relevant Courses: Econometrics, Statistics for Economic Analysis, Financial Economics, Linear Algebra, Calculus, Organic Chemistry / Laboratory, Advanced Laboratory: Materials Chemistry, Cells and Organisms

**EXPERIENCE**

**SECCO Petroleum Company**                                    Shanghai, CN

*Data Analyst Intern*                                 June 2017-August 2017 

Used SAP to itemize the price of crude oil product and calculate the costs of oil refining process. 

Collected and analyzed data from a pollution detection system and to make presentation on describing the data to help environmental groups decrease pollution (gas, water, and solid waste) generated by burning fuel.

**Brandeis Student Union**                                      Waltham, MA

*Representative of racial minority on Allocation Board*                    October 2015-October 2016

Utilized the school funding system to collect data and itemize the requests of funds from 260 student-run clubs and organization

Organized weekly A-board meetings to discuss approval of the request for funds, or to subsidize partially. Allocated approximately $3,000,000 efficiently on different student events and activities each semester

Led meetings with club leaders to help them solve problems about using the school funding system or how to using allocated funds on their club activities in efficient ways. 
 
**VOLUNTEER** 

**Lahey Hospital**                                           Burlington, MA                            
Hospital Helper                                 December 2014-December 2015                                                        
**Zoo Maria**                                                    Costa Rica
Wildlife-Protecting volunteer                                     July 2016

**SKILLS**
Computer: Microsoft Excel and Powerpoint, R, Stata, Mathematica, SAP
Language: Chinese (Native Speaker), Korean (Intermediate)
